### ISSUE TITLE
Not updating when activaring phisically

### ISSUE THREAD

**Issue by soth78** [guerrerotook/securitas-direct-new-api#1]
Hi,

I seems to be unable to configure the system so that, when I activate the alarm phsically or with the official app, home assistant knows and changes to armed

Could you help? 

Thanks!

**Comment by guerrerotook** [comment]
Hey @soth78, there is a way in the API to check what is the status of the alarm. 

In this [function](https://github.com/guerrerotook/securitas-direct-new-api/blob/main/custom_components/securitas_direct/__init__.py#L110), I check what is the status of the alarm every 5 minutes. That trigger the panel to check that status of the alarm and report back, so the component is automatically updating and calling the API. It should be a scenario where you change the arm status of your alarm using your key and Home Assistant will show another status but then in the next update you can see that it changes.

**Comment by soth78** [comment]
Hi!

I armed with the key, and it has passed mpre than 20' and it hasnt refreshed

Maybe the status pull isn't working. If I can share any useful info let me know

**Comment by soth78** [comment]
Hi,

Update: if u reboot the server, the status updates

@guerrerotook it think its not executing every 5min... Anyway to check this?

**Comment by guerrerotook** [comment]
[Here](https://github.com/guerrerotook/securitas-direct-new-api/blob/main/custom_components/securitas_direct/alarm_control_panel.py#L37) is how often the component is being updated and call the securitas direct API to refresh the state. 

If you want to enable the debug logs so you can see all traces for the component, 
```yml
logger:
  default: error
  logs:
    custom_components.securitas_direct: debug
```

**Take care with posting logs because it may include sensitive information like your username, password and session information.**

**Comment by soth78** [comment]
Hi!

After updating the code to the current build ots working lime a charm!!! 

Bravo!!!
