### ISSUE TITLE
I can only disarmed my alarm

### ISSUE THREAD

**Issue by nounckele** [guerrerotook/securitas-direct-new-api#233]
Hello, 
I got status from my alarm in home assistant and I can disarmed my alarm from home assistant too.
But I can't arm my alarm from home assistant.
No log when I do it. 
But when I start HA I got : "ERROR (MainThread) [homeassistant.helpers.service] Failed to load integration: securitas"
Do you have any idea ?
Thanks a lot for your job

**Comment by Cavech84** [comment]
Hello, i have the same problem.

**Comment by khchan3501** [comment]
I had the same issue earlier, but I might have figured the cause.

Try deselect the "Check alarm panel's status in every request (not recommended)" option, at least this method worked for me.

This option is located on the "Integration entries", there you should see your username, and there is a "CONFIGURE" button, press it, then you should see that "Check alarm..." option

The reason I tried it, was because when I went back to my official Verisure app, and checked on the timeline, there were constant non-stop entries of "Alarm Status Request", then I turned the option off, and went back to the official Verisure app, all those entries has stopped, then tried arming and disarming has worked fine thereafter.

Hope this helps everyone.


![Screenshot_20240616_025706_Home Assistant](https://github.com/guerrerotook/securitas-direct-new-api/assets/495468/f8a316aa-3fb8-4bd1-8778-05679cbb3e9f)

**Comment by nounckele** [comment]
Thanks for your answer @khchan3501 but the "Check alarm panel's" was already uncheck.
And I my timeline in Verisure app I didn't see any request for arming my alarm.
Disarmed alarm work's fine.

**Comment by lucamarchetello** [comment]
i have the same problem, any suggestions?

**Comment by nounckele** [comment]
SOLVED : I just remove PIN Code from configuration
