### ISSUE TITLE
Can't disarm since   V2.1.0.0

### ISSUE THREAD

**Issue by bilbon0bud** [guerrerotook/securitas-direct-new-api#90]
Hello

with release 2.1.0.0 and latest Home assistant, i can arm my alarm but i can't desearm it.

Best Regards

**Comment by bilbon0bud** [comment]
In the verisure logs, i can only see "Consultation de l 'état" (check state) when trying to disarm.

**Comment by yyounes75** [comment]
Hi,

Same for me, the components can not disable the alarm. When we trigger the service "alarm_control_panel.alarm_disarm", it will check the status of the alarm (which work) and not disarm it.

```
2022-10-17 12:29:55.376 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Making request with device_id XXXXX, uuid XXXXX and idDeviceIndigitall 
2022-10-17 12:29:56.832 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] --------------Response--------------
2022-10-17 12:29:56.832 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] {"data":{"xSCheckAlarmStatus":{"res":"OK","msg":"Votre alarme a été activée en mode Nuit","status":"Q","numinst":"XXXXX","protomResponse":"Q","protomResponseDate":"2022-10-17 12:29:48.310"}}}
```

Same problem as this issue https://github.com/guerrerotook/securitas-direct-new-api/issues/71

**Comment by sergiomart96** [comment]
teneis que configurar el code

**Comment by rogelio-o** [comment]
The problem is the commit [8e8082c](https://github.com/guerrerotook/securitas-direct-new-api/commit/8e8082caa2e7c923288856779db08c06a38c40f7). After removing the commit it works. With the conditional of the commit we are comparing strings with integer and never making the next conditional pass with `configured_code (string) == code (integer)`.

**Comment by sergiomart96** [comment]
pues la verdad esque puse el code y me desarmo, por eso lo comente, pero estaba claro que el error estaba en el code, muy bien visto @rogelio-o, me imagino que habrá que esperar ha actualización o seguir buscando una solucion

**Comment by bilbon0bud** [comment]
@rogelio-o is it possible to have the file with the correction ?
Best Regards

**Comment by Javvaz** [comment]
Correct. I just commented the below lines of the alarm_control_panel.py and now it is again able to disarm from away, home, or night status, however the issue with custom_by_pass status remains, since is not able to disarm from custom_by_pass status never more.

![image](https://user-images.githubusercontent.com/98023153/201079582-9b921f3b-04c5-4055-93d1-6c6bdd8418ce.png)

**Comment by bilbon0bud** [comment]
Thx, it works with this trick.

Have a nice day

**Comment by glebiller** [comment]
@guerrerotook This bug has been closed, however, I do not see any PR to actually fix the bug, am I missing something?
Manually editing the file does not seems to be the best fix solution!
